apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-700"
  name: monitoring
  namespace: argocd
 
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default 
  syncPolicy:
   automated: {}
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan
    - ServerSideApply=true
  sources:
  - repoURL: 'https://victoriametrics.github.io/helm-charts/'
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.24.5
    helm:
      values: |-
         victoria-metrics-operator:
            image:
              repository: {{ .Values.spec.registry }}/victoriametrics/operator       
            env:
            - name: VM_VMALERTDEFAULT_CONFIGRELOADIMAGE    
              value: {{ .Values.spec.registry }}/jimmidyson/configmap-reload:v0.3.0
            - name: VM_VMALERTMANAGER_CONFIGRELOADERIMAGE	
              value: {{ .Values.spec.registry }}/jimmidyson/configmap-reload:v0.3.0  
            - name: VM_VMAGENTDEFAULT_CONFIGRELOADIMAGE	
              value: {{ .Values.spec.registry }}/prometheus-operator/prometheus-config-reloader:v0.68.0  
            cleanupImage:
               repository: {{ .Values.spec.registry }}/bitnami/kubectl
         vmsingle:
            enabled: false      
         vmcluster:
            enabled: true
            spec:
              retentionPeriod: "30d"
              vmstorage:
                 image:
                    repository: {{ .Values.spec.registry }}/victoriametrics/vmstorage
                 storage:
                    volumeClaimTemplate:
                       spec:
                         storageClassName: "k8s-lvm-sc"  
                         resources:
                            requests:
                               storage: 10Gi
                 resources:
                    limits:
                       cpu: 2000m
                       memory: 2Gi
                    requests: 
                       cpu: 500m
                       memory: 512Mi
              vmselect:
                 image:
                    repository: {{ .Values.spec.registry }}/victoriametrics/vmselect
                 storage:
                    volumeClaimTemplate:
                       spec:
                         storageClassName: "k8s-lvm-sc"   
                         resources:
                            requests:
                               storage: 2Gi
                 resources:
                    limits:
                       cpu: 500m
                       memory: 512Mi
                    requests: 
                       cpu: 500m
                       memory: 512Mi   
              vminsert:
                 image:
                    repository: {{ .Values.spec.registry }}/victoriametrics/vminsert
                 resources:
                    limits:
                       cpu: 500m
                       memory: 512Mi
                    requests: 
                       cpu: 500m
                       memory: 512Mi  
            ingress:
               select:
                  enabled: true
                  ingressClassName: "nginx"
                  annotations:
                     acme.cert-manager.io/http01-edit-in-place: 'true'
                     cert-manager.io/cluster-issuer: letsencrypt-cloudns                   
                  hosts:
                    - vmselect.tools.mobintadbir.ir
                  tls:
                    - secretName: vmselect-acme-issuer
                      hosts:
                        - vmselect.tools.mobintadbir.ir                       

               insert:
                  enabled: true
                  ingressClassName: "nginx"
                  annotations:
                    acme.cert-manager.io/http01-edit-in-place: 'true'
                    cert-manager.io/cluster-issuer: letsencrypt-cloudns                   
                    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
                    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
                    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
                    nginx.ingress.kubernetes.io/client-header-buffer-size: "50m"
                  hosts:
                    - vminsert.tools.mobintadbir.ir
                  tls:
                    - secretName: vminsert-acme-issuer
                      hosts:
                        - vminsert.tools.mobintadbir.ir                                
         alertmanager:
             spec:
                image: 
                  repository: {{ .Values.spec.registry }}/prometheus/alertmanager
             config:
                 templates:
                   - "/etc/vm/configs/**/*.tmpl"
                 route:
                   group_by: ["alertgroup", "job"]
                   group_wait: 30s
                   group_interval: 5m
                   repeat_interval: 1h
                   receiver: "blackhole"
                   routes:
                     - matchers:
                         - severity=~"critical"
                       group_by: ["alertgroup", "job"]
                       receiver: devops
             
                 inhibit_rules:
                   - target_matchers:
                       - severity=~"warning|info"
                     source_matchers:
                       - severity=critical
                     equal:
                       - cluster
                       - namespace
                       - alertname
                   - target_matchers:
                       - severity=info
                     source_matchers:
                       - severity=warning
                     equal:
                       - cluster
                       - namespace
                       - alertname
                   - target_matchers:
                       - severity=info
                     source_matchers:
                       - alertname=InfoInhibitor
                     equal:
                       - cluster
                       - namespace

                 receivers:
                   - name: blackhole
                   - name: devops
                     webhook_configs:
                       - url: 'http://192.168.200.44/webhook/ad794e23-cb18-4dbf-9644-263624fd5b90/alert_devops'
                         send_resolved: true
                   
             
         vmalert:
            spec:
               image: 
                 repository: {{ .Values.spec.registry }}/victoriametrics/vmalert
         vmagent:
             spec:
                image: 
                  repository: {{ .Values.spec.registry }}/victoriametrics/vmagent
                externalLabels:
                  cluster: tools
                inlineScrapeConfig: |
                  - job_name: "cdn"
                    static_configs:
                    - targets: ["192.168.207.250:9100"]      
                  - job_name: "cdn_vts"
                    static_configs:
                    - targets: ["192.168.207.250:8080/status"]
                  - job_name: "dorsa-postgres"
                    static_configs:
                    - targets: ["192.168.200.100:9187"]
                  - job_name: "kafka-exporter"
                    static_configs:
                    - targets: ["192.168.200.100:9308"]
         grafana:
           global:
             imageRegistry: {{ .Values.spec.registry }}
           sidecar:
              dashboards:
                multicluster: true
           adminPassword: 55UItzBingDjcbEzr5Tz09ETcHMU6imT3h7Oyxm0   
           persistence:
             enabled: true
             storageClassName: k8s-lvm-sc
             size: 2Gi  
           initChownData:
             enabled: false
             image:
               repository: busybox
               tag: latest
          #   datasources.yaml:
          #     apiVersion: 1
          #     datasources:
          #     - name: Prometheus
          #       type: prometheus
          #       url: http://prometheus-prometheus-server
          #       access: proxy
          #       isDefault: true  
           downloadDashboardsImage:
               registry: {{ .Values.spec.registry }}
           
           ingress:
             enabled: true
             ingressClassName: public
             hosts:
               - fanoos.mobintadbir.ir
           #plugins:
           #  - https://repo.mobintadbir.ir/repository/github.com/clickhouse-datasource/releases/download/v4.5.0/grafana-clickhouse-datasource-4.5.0.zip,clickhouse-datasource
           #  - https://repo.mobintadbir.ir/repository/storage.googleapis.com/integration-artifacts/marcusolsson-treemap-panel/release/2.0.1/any/marcusolsson-treemap-panel-2.0.1.any.zip,marcusolsson-treemap-panel
           #  - https://repo.mobintadbir.ir/repository/github.com/grafana/google-sheets-datasource/releases/download/v2.0.1/grafana-googlesheets-datasource-2.0.1.zip,google-sheets-datasource  
           #  - https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/netsage-bumpchart-panel/release/1.1.3/netsage-bumpchart-panel-1.1.3.zip,netsage-bumpchart-panel
           #  - https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/anyline-rangeslider-panel/release/1.2.9/anyline-rangeslider-panel-1.2.9.zip,anyline-rangeslider-panel
           #  - https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/integrationmatters-comparison-panel/release/1.1.0/integrationmatters-comparison-panel-1.1.0.zip,integrationmatters-comparison-panel
           #  - https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/marcusolsson-calendar-panel/release/3.9.0/marcusolsson-calendar-panel-3.9.0.zip,marcusolsson-calendar-panel
           #  - https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/volkovlabs-echarts-panel/release/6.6.0/volkovlabs-echarts-panel-6.6.0.zip,volkovlabs-echarts-panel
           #  - https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/digrich-bubblechart-panel/release/2.0.1/digrich-bubblechart-panel-2.0.1.zip,digrich-bubblechart-panel
           #extraInitContainers:
           #  - name: local-plugins-downloader
           #    image: docker.mobintadbir.ir/busybox
           #    command:
           #      - /bin/sh
           #      - -c
           #      - |
           #        set -euo pipefail
           #        mkdir -p /var/lib/grafana/plugins
           #        cd /var/lib/grafana/plugins
           #        wget --no-check-certificate https://repo.mobintadbir.ir/repository/github.com/grafana/clickhouse-datasource/releases/download/v4.5.0/grafana-clickhouse-datasource-4.5.0.zip -O clickhouse-grafana.zip
           #        unzip clickhouse-grafana.zip
           #        rm clickhouse-grafana.zip
           #        wget --no-check-certificate https://repo.mobintadbir.ir/repository/storage.googleapis.com/integration-artifacts/marcusolsson-treemap-panel/release/2.0.1/any/marcusolsson-treemap-panel-2.0.1.any.zip -O treemap-grafana.zip
           #        unzip treemap-grafana.zip
           #        rm treemap-grafana.zip
           #        wget --no-check-certificate https://repo.mobintadbir.ir/repository/github.com/grafana/google-sheets-datasource/releases/download/v2.0.1/grafana-googlesheets-datasource-2.0.1.zip -O grafana-googlesheets.zip
           #        unzip grafana-googlesheets.zip
           #        rm grafana-googlesheets.zip
           #        wget --no-check-certificate https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/anyline-rangeslider-panel/release/1.2.9/anyline-rangeslider-panel-1.2.9.zip -O rangeslider.zip
           #        unzip rangeslider.zip
           #        rm rangeslider.zip
           #        wget --no-check-certificate https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/integrationmatters-comparison-panel/release/1.1.0/integrationmatters-comparison-panel-1.1.0.zip -O comparison.zip
           #        unzip comparison.zip
           #        rm comparison.zip
           #        wget --no-check-certificate https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/marcusolsson-calendar-panel/release/3.9.0/marcusolsson-calendar-panel-3.9.0.zip -O calendar.zip
           #        unzip calendar.zip
           #        rm calendar.zip
           #        wget --no-check-certificate https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/volkovlabs-echarts-panel/release/6.6.0/volkovlabs-echarts-panel-6.6.0.zip -O echarts.zip
           #        unzip echarts.zip
           #        rm echarts.zip
           #        wget --no-check-certificate https://repo.mobintadbir.ir/repository/storage.googleapis.com/plugins-community/digrich-bubblechart-panel/release/2.0.1/digrich-bubblechart-panel-2.0.1.zip -O bubblechart.zip
           #        unzip bubblechart.zip
           #        rm bubblechart.zip
           #    volumeMounts:
           #      - name: grafana-plugins
           #        mountPath: /var/lib/grafana
           #extraContainerVolumes:
           #  - name: grafana-plugins
           #    emptyDir: {}
           #extraVolumeMounts:
           #  - name: grafana-plugins
           #    mountPath: /var/lib/grafana/plugins
         prometheus-node-exporter:
             image:
                registry: {{ .Values.spec.registry }}
         kube-state-metrics:
             image:
                registry: {{ .Values.spec.registry }}
         prometheus-operator-crds:
            enabled: true      